Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2023-09, with the labels that each got.

#142 fix(helm-configuration): increase initialDelaySeconds for DEV env
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#151 Chk 1921 v2 event deserialization
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidEventException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundQueueConsumer.kt
Labels: size/large

#146 fix(event parsing): invalid event written to dead-letter queue
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidEventException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundEventsConsumerTests.kt
Labels: patch, chart-patch

#147 [CHK-1921]: refactor(v2): handle different event versions
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/RedisConfig.java
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/BadTransactionStatusException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidEventException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/NoRetryAttemptsLeftException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/TooLateRetryAttemptException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/TransactionEventNotFoundException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/TransactionEventsInconsistentException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/TransactionEventsPreconditionsNotMatchedException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/repositories/TransactionsEventStoreRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/repositories/TransactionsViewRepository.java
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/ClosureRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/NotificationRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/RefundRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/RetryEventService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/ClosureRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/NotificationRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RefundRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RetryEventService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialMailUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilder.kt
  src/main/resources/logback-spring.xml
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/ClosureRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/NotificationRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/RefundRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialMailUtilsTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilderTest.kt
Labels: size/small

#156 Fix test assertions
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt
Labels: size/small, patch, chart-patch
