Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2023-10, with the labels that each got.

#154 [CHK-1863] feat(NPG): implement npg refund logic
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/PaymentGatewayClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/service/RefundServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#158 CHK-1974: feat logo mail npg
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, chart-minor, minor

#161 feat: CHK-1929 add clientid used for closepayment
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#163 chore(deps): [CHK-2004] - update `commons` version to 0.26.0
  pom.xml
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, patch, chart-patch, 🤖 automatic, commons

#162 [CHK-1968] improve npg client invocation
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
Labels: size/small, patch, chart-patch
