Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2024-09, with the labels that each got.

#319 feat: [CHK-3108] Provide iuv as notice id for wisp deprecation
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/WispDeprecation.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/WispDeprecationTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, chart-minor, minor

#326 fix: add handling for RICO redirect method code
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, chart-minor, minor

#323 [CHK-3136] remove xpay vpos references
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/PaymentGatewayClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/PaymentGatewayClientTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/ClosureRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/NotificationRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RefundRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#329 fix: increase PROD memory
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#330 add wisp redirect client in refund chain
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
Labels: size/small, patch, chart-patch

#321 feat: zero downtime deploy pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/receivers-commands/polling-receivers-status.yml
  .devops/azure-templates/receivers-commands/send-receiver-command.yml
  .devops/azure-templates/start-receivers.yml
  .devops/azure-templates/stop-receivers.yml
  .devops/deploy-pipelines.yml
Labels: size/large, skip-release

#331 fix: pipeline dependencies
  .devops/deploy-pipelines.yml
Labels: size/small, chart-minor, minor

#332 fix: pipeline checkout release version
  .devops/deploy-pipelines.yml
Labels: size/small, patch, chart-patch

#333 [CHK-3215] feat(refund): add refund transaction case
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/ClosePaymentErrorResponseException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
Labels: size/small, chart-minor, minor

#337 fix: handle pending authorization status in GET order
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidNpgOrderStateException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/RefundError.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/RefundNotAllowedException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NpgService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/resources/application.test.properties
Labels: patch, chart-patch

#338 fix: increase uat/prod cpu limits
  helm/Chart.lock
  helm/Chart.yaml
  helm/charts/microservice-chart-2.3.1.tgz
  helm/charts/microservice-chart-2.8.0.tgz
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch
