Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2024-05, with the labels that each got.

#255 fix: [CHK-2711] Request refund NPG data on Auth Requested transactions
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/RefundError.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
Labels: size/small, chart-minor, minor

#242 [CHK-2792] feat(closepayment): implement `closePayment` for PayPal payments
  helm/values-dev.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialDataUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialMailUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v1/UserReceiptMailBuilder.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialDataUtilsTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v1/UserReceiptMailBuilderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/large, patch, chart-patch

#261 fix: ecommerce commons ref
  pom.xml
Labels: size/small, patch, chart-patch

#258 [CHK-2812] feat(getstate): forward NPG `validationServiceId` if present in NPG `getState`
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, patch, chart-patch

#259 feat: enable beta for dev
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#262 feat: user notification for carts
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, chart-minor, minor

#267 fix: update myBankTransactionId field case
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, patch, chart-patch

#263 [CHK-2811] feat(getstate): forward `errorCode` from NPG when calling `getState`
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
Labels: size/small, patch, chart-patch

#269 [CHK-2835] Using get orders NPG when transaction stuck in AUTH_REQUESTED
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidNPGResponseException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidNpgOrderStateException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/RefundError.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/AuthorizationStateRetrieverRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/ClosureRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/NotificationRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RefundRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RetryEventService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NpgService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/AuthorizationStateRetrieverRetryServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/ClosureRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/NotificationRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RefundRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/NpgTestUtils.kt
Labels: size/large, chart-minor, minor

#270 Chk 2785 implementation tuning
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/PaymentGatewayClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesProducerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
Labels: size/small, patch, chart-patch

#275 fix: [CHK-2880] Using common with no parent tracing fix
  pom.xml
Labels: size/small, patch, chart-patch

#278 fix: Revert ecommerce-common no parent tracing
  pom.xml
Labels: size/small, patch, chart-patch

#280 chore(NPG-conf): add MyBank and cards required PSP api keys
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#282 fix: don't fail the pipeline if the beta deployment does not exist
  .devops/deploy-pipelines.yml
Labels: size/small, patch, chart-patch

#283 Chk 2850 spring integration instrumentation
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
Labels: size/small, patch, chart-patch
