Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2024-06, with the labels that each got.

#285 fix: [CHK-2850] Filter spring integration channels otel instrumentation
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#286 fix: [CHK-2580] Remove spring integration instrumentation
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#279 [CHK-2868] Add touchpoint parameter to redirectUrls search.
  helm/values-dev.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/RedirectConfigurationBuilder.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/RedirectConfigurationBuilderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
Labels: size/small, chart-minor, minor

#289 chore(conf npg cards): add WOLLNLB1 psp id
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#291 [CHK-2918] fix: take NPG order id from authorization data when invoking `GET order/:orderId`
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverServiceTest.kt
Labels: size/small, patch, chart-patch

#292 [CHK-2904] change fields sent to notifications service
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, patch, chart-patch

#294 update psp list
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#293 fix(npg-client): add trailing slash to GET orders
  pom.xml
Labels: size/small, patch, chart-patch

#296 chore(conf): add redirect psp api keys
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#298 [CHK-2976] fix: set `additionalPaymentInformations` timestamps to naive date time format
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, patch, chart-patch

#299 feat(pspList): add pspId IFSPIT21 to pspIdList
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#300 Chk 2992 shared api key pdv
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/SecretConfigurations.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialDataUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/ConfidentialDataUtilsTest.kt
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch
