Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2024-02, with the labels that each got.

#207 feat: [CHK-2425] [CHK-2394] - handle redirect payment flows transactions
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/small, chart-minor, minor

#210 [CHK-2277] feat(close payment): eurocents in transaction details
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, patch, chart-patch

#211 fix(chart): [CHK-2437] - add deployment strategy for event dispatcher
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#212 [CHK-2334] fix(deps): mark `netty-resolver-dns-native-macos` dependency for test only as it causes memleak in prod
  pom.xml
Labels: size/small, patch, chart-patch

#215 fix(refund): handle refund logic for close payment KO responses
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/BadClosePaymentRequest.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/ClosePaymentErrorResponseException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/CommonTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/CommonTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
Labels: size/large, patch, chart-patch

#218 fix: extract node close payment error response
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
Labels: size/small, patch, chart-patch

#217 chore(conf): change uat blue env to point dedicated queues
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#219 fix: add cache delete after user transaction cancellation close payment
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
Labels: size/small, patch, chart-patch

#214 [CHK-2444] Correlation id into npg refund request
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt
Labels: size/small, chart-minor, minor

#221 chore(command collection): update base path
  command-postman-collection/commands.postman_collection.json
Labels: size/small, skip-release

#216 [CHK-2457] Handling missing NPG notification url invoking getState to patch auth request
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/TransactionsServiceClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesProducerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidNPGPaymentGatewayException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidPaymentGatewayException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/NpgBadRequestException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/NpgPaymentGatewayStateException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/NpgServerErrorException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/PatchAuthRequestErrorResponseException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/UnauthorizedPatchAuthorizationRequestException.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionAuthorizationRequestedQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionAuthorizationRequestedQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/AuthorizationStateRetrieverRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NpgStateService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/TransactionsServiceClientTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionAuthorizationRequestedQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionAuthorizationRequestedQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/AuthorizationStateRetrieverRetryServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NpgStateServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#223 fix: tuning mongo parameters
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch

#228 chore(open-telemetry-agent): [CHK-2534] - update agent version
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: size/small, patch, chart-patch
