Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2024-07, with the labels that each got.

#302 fix(conf): add NPG cards required api keys
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#304 [CHK-3008]- Bancomat pay close payment
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, chart-minor, minor

#303 feat: [CHK-3007] - use bpayEndToEndId as paymentEndToEndId
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, chart-minor, minor

#306 [CHK-3010] mybank close payment
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, chart-minor, minor

#305 [CHK-3011] mybank get state
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/EndToEndId.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, chart-minor, minor

#314 chore: increase min replicas
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#311 [CHK-3016] feat(applepay + satispay) : update close payment request body
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: chart-minor, minor

#310 feat(npg-apm): add configuration for apple pay and satispay
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/NpgPspsApiKeyConfigBuilder.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#312 [CHK-3034] feat: enable PSP iConto for cards payments in prod
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#317 feat: trace close payment requests
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/OpenTelemetryConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
Labels: size/small, chart-minor, minor
