Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2024-01, with the labels that each got.

#190 fix: write event to dead letter queue
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
Labels: size/small, patch, chart-patch

#191 fix(refund): [CHK-2264] - perform retries when PGS transaction status is CREATED
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
Labels: size/small, patch, chart-patch

#192 fix(conf): restoring send payment result timeout to 65 mins
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#203 feat: CHK-1987 disable apm log send
  helm/values-prod.yaml
Labels: size/small, chart-minor, minor

#201 [CHK-2388] - part5 feat: add junit tests
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherCommandsTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherReceiverStatusTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/RedisStreamConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiverStatusPollerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiversServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/InboundChannelAdapterHandlerServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/stream/RedisStreamMessageSourceTest.kt
Labels: size/large

#197 [CHK-2388] - part 1 receiver stop api and env vars
  .env.example
  Dockerfile
  README.md
  api-spec/event-dispatcher-api.yaml
  command-postman-collection/commands.postman_collection.json
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/ControlBusConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/RedisConfig.java
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/RedisStreamEventControllerConfigs.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherCommandsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherReceiverStatusTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/RedisConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/bean/ReceiverStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/bean/ReceiversStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/bean/Status.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/stream/RedisStreamMessageSource.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/stream/StreamConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiController.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/NoEventReceiverStatusFound.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/RedisStreamConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/commands/EventDispatcherCommandMixin.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/commands/EventDispatcherGenericCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/commands/EventDispatcherReceiverCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiverService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiverStatusPoller.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/InboundChannelAdapterLifecycleHandlerService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/validation/BeanValidationConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/validation/CustomLocalValidatorFactoryBean.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/validation/SuspendAwareKotlinParameterNameDiscoverer.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherCommandsTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherReceiverStatusTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/RedisStreamConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiverStatusPollerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiversServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/InboundChannelAdapterLifecycleHandlerServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/stream/RedisStreamMessageSourceTest.kt
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#202 [CHK-2371] feat(closePayment): handle CLOSURE_REQUESTED event
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Labels: size/large, chart-minor, minor
