Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2025-07, with the labels that each got.

#408 feat: api key filter
  .devops/azure-templates/receivers-commands/polling-receivers-status.yml
  .devops/azure-templates/receivers-commands/send-receiver-command.yml
  .devops/azure-templates/start-receivers.yml
  .devops/azure-templates/stop-receivers.yml
  .devops/deploy-pipelines.yml
  .env.example
  README.md
  api-spec/event-dispatcher-api.yaml
  command-postman-collection/commands.postman_collection.json
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/filters/ApiKeyFilter.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiControllerTest.kt
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#412 [PIDM-753] google pay close payment missing
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, patch, chart-patch

#409 feat: [CHK-4221] bump java version 17 -> 21
  .devops/code-review-pipelines.yml
  .github/workflows/semver_release.yaml
  .java-version
  Dockerfile
  api-spec/event-dispatcher-api.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiController.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
Labels: size/small, major, chart-major

#414 [PIDM-410] feat(psp): add new mooney bic code
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#416 feat: integrate pending status tests in pipelines
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#417 [PIDM-753] feat(close-payment): add google pay case
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
Labels: size/small, patch, chart-patch
