Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2025-01, with the labels that each got.

#364 feat: [CHK-3626] Adding authorizationRequestId to additionalPaymentInformations for apple pay closePayment (v2)
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Labels: size/small, chart-minor, minor

#365 feat: [CHK-3347] Added logic to warmup lazy beans
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/stream/StreamConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionAuthorizationOutcomeWaitingQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionAuthorizationRequestedQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/InboundChannelAdapterLifecycleHandlerService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/warmup/ServicesWarmup.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/warmup/annotations/WarmupFunction.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/warmup/utils/EventsUtil.java
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/warmup/utils/WarmupRequests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/warmup/utils/WarmupRequestsTest.kt
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#366 [CHK-3648] feat: add events integration tests into code review
  .devops/code-review-pipelines.yml
Labels: size/small, skip-release
