Repository pagopa/pagopa-ecommerce-event-dispatcher-service, pull requests merged in 2025-04, with the labels that each got.

#374 [CHK-4003] Added api key in closePayment
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#378 feat: use patch auth request V2
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/TransactionsServiceClient.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/TransactionsServiceClientTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
Labels: size/small, chart-minor, minor

#380 feat: add google pay NPG APM api key management
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/NpgPspsApiKeyConfigBuilder.kt
  src/main/resources/application.properties
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#382 [PIDM-454] fix: expanded prod rollback trigger conditions
  .devops/deploy-pipelines.yml
Labels: size/small, chart-minor, minor

#384 feat: [CHK-4073] add custom opentelemetry spans for final transactions statuses
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/OpenTelemetryConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TransactionTracing.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TransactionTracingTest.kt
Labels: chart-minor, minor

#383 [CHK-4071] chore(v1-handlers): remove unused events queue consumers
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundQueueConsumer.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/warmup/utils/WarmupRequestsTest.kt
Labels: size/large, chart-minor, minor

#386 [CHK-4071] chore(v1-handlers): remove unused v1 service/utils
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/ClosureRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/NotificationRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/RefundRetryService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/RetryEventService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeService.kt
  src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v1/UserReceiptMailBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/CommonTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/ClosureRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/NotificationRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v1/RefundRetryServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v1/UserReceiptMailBuilderTest.kt
Labels: size/large, chart-minor, minor

#388 fix(semver): pom version bump
  .github/workflows/semver_release.yaml
Labels: size/small, patch, chart-patch

#389 chore: trigger pipeline
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, patch, chart-patch

#391 fix: add condition to skip release
  .github/workflows/semver_release.yaml
Labels: skip-release

#392 Chk 4095 fix deploy pipeline
  .github/workflows/check_pr.yml
Labels: size/small, patch, chart-patch

#393 fix: version bump script
  .github/workflows/semver_release.yaml
Labels: size/small, chart-patch, ignore-for-release
